//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID_address { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> House { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
